ERROR:__main__:Erro ao enviar e-mail: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
Traceback (most recent call last):
  File "C:\Users\x17859816\Desktop\PaperControlSystem\app.py", line 399, in enviar_email
    with smtplib.SMTP(smtp_server, smtp_port) as smtp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 851, in create_connection
    raise exceptions[0]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
INFO:werkzeug:127.0.0.1 - - [08/Jan/2024 08:58:29] "POST /ajudaOZe HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Jan/2024 08:58:29] "[36mGET /static/styles/ajudaOZe.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [08/Jan/2024 08:58:29] "[36mGET /static/images/exitbutton.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [08/Jan/2024 08:58:29] "[36mGET /static/images/background-zezinho.png HTTP/1.1[0m" 304 -
INFO:werkzeug: * Detected change in 'C:\\Users\\x17859816\\Desktop\\PaperControlSystem\\app.py', reloading
INFO:werkzeug: * Restarting with stat
